"""add_salary_discounts_remove_commission

Revision ID: 012ea3264d2e
Revises: e0619f04fba6
Create Date: 2026-02-28 21:03:11.656489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012ea3264d2e'
down_revision: Union[str, None] = 'e0619f04fba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discounts_owner_id', 'discounts', ['owner_id'], unique=False)
    op.add_column('employees', sa.Column('salary', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    op.drop_column('employees', 'commission_rate')
    op.add_column('sessions', sa.Column('discount_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    op.create_foreign_key(None, 'sessions', 'discounts', ['discount_id'], ['id'])
    op.drop_column('sessions', 'owner_profit')
    op.drop_column('sessions', 'employee_cut')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('employee_cut', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('owner_profit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'discount_amount')
    op.drop_column('sessions', 'discount_id')
    op.add_column('employees', sa.Column('commission_rate', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
    op.drop_column('employees', 'salary')
    op.drop_index('ix_discounts_owner_id', table_name='discounts')
    op.drop_table('discounts')
    # ### end Alembic commands ###
