"""Add cost type

Revision ID: 06b28ee65da2
Revises: 012ea3264d2e
Create Date: 2026-03-01 20:48:49.666438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b28ee65da2'
down_revision: Union[str, None] = '012ea3264d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costs', sa.Column('type', sa.String(length=20), server_default='variable', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('costs', 'type')
    # ### end Alembic commands ###
