"""remove_phone_from_employees

Revision ID: 56c8e72e3056
Revises: ef2c744c6a2e
Create Date: 2026-03-02 19:55:46.254847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c8e72e3056'
down_revision: Union[str, None] = 'ef2c744c6a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
