"""Make cost month nullable

Revision ID: ef2c744c6a2e
Revises: 06b28ee65da2
Create Date: 2026-03-01 20:56:50.956046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2c744c6a2e'
down_revision: Union[str, None] = '06b28ee65da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('costs', 'month',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('costs', 'month',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    # ### end Alembic commands ###
